name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build:

    name: Python ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    defaults:
      run:
        shell: bash -l {0}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: osmnx-dev
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
          environment-file: environment-dev.yml

      - name: Install OSMnx
        shell: bash
        run: |
          conda list
          conda info --all
          python setup.py install
          conda list
          conda info --all

      - name: Lint code
        shell: bash
        run: |
          isort . --check-only
          black . --line-length 100 --check --diff
          flake8 .
          pydocstyle .

      - name: Test docs
        shell: bash
        run: make -C ./docs html

      - name: Test code
        shell: bash
        run:
          coverage run --source ./osmnx --module pytest --verbose
          coverage xml -i
          coverage report -m

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
