name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build:

    name: Python ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9"]

    defaults:
      run:
        shell: bash -l {0}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 1
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('environment-dev.yml') }}

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh
          show-channel-urls: true
          use-only-tar-bz2: true
          channel-priority: strict
          activate-environment: osmnx-dev

      - name: Install dependencies
        run: |
          mamba env update -f environment-dev.yml
          conda list
          conda info --all

      - name: Install OSMnx
        run: python setup.py install

      - name: Lint code
        run: |
          isort . --check-only
          black . --line-length 100 --check --diff
          flake8 .
          pydocstyle .

      - name: Test docs
        run: make -C ./docs html

      - name: Test code
        run: |
          coverage run --source ./osmnx --module pytest --verbose
          coverage xml -i
          coverage report -m

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
